server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springuser
    url: jdbc:mysql://mysql_db:3306/growbiz
    password: spring
  jpa:
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: asdcgrowbiz@gmail.com
    password: mvna jrcg ruoh gvry
    port: 587
  thymeleaf:
    prefix: classpath:/template/
keys:
  stripeAPIKey: sk_test_51O9V7jI2En4LSMTzAOnJd4GnWzNvPgFqXvHvdbQv0JYFW9VF8k3fqhL6I2chjQ1Svjj2m4J9hqYfcWwQl5SWUAL900iPzxM23r
  stripeWebhookSecret: whsec_5yhM2hwS7ZdLDY0JwiY5mJsCcHLK9BfE